#!/usr/bin/env python3
import argparse
from pathlib import Path

DEFAULT_TEST_NUM_FILES = 50
DEFAULT_MIN_SIZE = 5 * 1024
DEFAULT_MAX_SIZE = 400 * 1024
BASE_SERVER_FILE_COUNT = 66
LINE_BYTES = 16


def test_file_size(index: int, count: int, min_size: int, max_size: int) -> int:
    if count <= 1:
        return min_size
    return min_size + ((max_size - min_size) * index) // (count - 1)


def test_file_byte(file_index: int, byte_offset: int) -> int:
    return (file_index * 7 + byte_offset) & 0xFF


def write_filedata(out_path: Path, count: int, min_size: int, max_size: int) -> None:
    with out_path.open('w', encoding='utf-8') as fh:
        fh.write('#pragma once\n\n')
        fh.write('// Generated by generate_test_headers.py.\n\n')
        for test_index in range(count):
            file_number = BASE_SERVER_FILE_COUNT + test_index + 1
            file_length = test_file_size(test_index, count, min_size, max_size)
            fh.write(f'static const unsigned char file{file_number}[{file_length}] = {{')
            for offset in range(file_length):
                if offset % LINE_BYTES == 0:
                    fh.write('\n\t')
                fh.write(f'0x{test_file_byte(test_index, offset):02x}, ')
            fh.write('\n};\n')


def write_filemetadata(out_path: Path, count: int, min_size: int, max_size: int) -> None:
    with out_path.open('w', encoding='utf-8') as fh:
        fh.write('#pragma once\n\n')
        fh.write('// Generated by generate_test_headers.py.\n\n')
        for test_index in range(count):
            file_number = BASE_SERVER_FILE_COUNT + test_index + 1
            file_length = test_file_size(test_index, count, min_size, max_size)
            file_path = f'/testfile{test_index + 1:03d}.html'
            fh.write(
                f'static const ServerFile f{file_number} = {{ "{file_path}", "text/html", '
                f'file{file_number}, {file_length} }};\n'
            )
        fh.write('\n')
        refs = [f'f{i}' for i in range(1, BASE_SERVER_FILE_COUNT + count + 1)]
        fh.write(
            f'static const std::array<ServerFile, {BASE_SERVER_FILE_COUNT + count}> ServerFiles = {{ '
            + ', '.join(refs)
            + ' };\n'
        )


def main() -> None:
    parser = argparse.ArgumentParser(description='Generate Linux test filesystem headers.')
    parser.add_argument('output_dir', help='Directory to place filedata-test.h and filemetadata-test.h')
    parser.add_argument('--count', type=int, default=DEFAULT_TEST_NUM_FILES)
    parser.add_argument('--min-size', type=int, default=DEFAULT_MIN_SIZE)
    parser.add_argument('--max-size', type=int, default=DEFAULT_MAX_SIZE)
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    write_filedata(out_dir / 'filedata-test.h', args.count, args.min_size, args.max_size)
    write_filemetadata(out_dir / 'filemetadata-test.h', args.count, args.min_size, args.max_size)


if __name__ == '__main__':
    main()
