data = {
    "./srcfiles/index.html": ( "/index.html", "text/html" ),
    "./srcfiles/404.html": ( "/404.html", "text/html" ),
    "./srcfiles/image/favicon.ico": ( "/favicon.ico", "img/png" ),
    "./srcfiles/image/falcon-robotics.jpg": ( "/falcon-robotics.jpg", "img/jpg" ),
    "./srcfiles/image/esp32-pong-logo.png": ( "/esp32-pong-logo.png", "img/png" ),

    "./srcfiles/css/bootstrap.css": ( "/css/bootstrap.css", "text/css" ),
    "./srcfiles/css/globalstyles.css": ( "/css/globalstyles.css", "text/css" ),
    "./srcfiles/css/fontawesome/all.min.css": ( "/css/fontawesome/css/all.min.css", "text/css" ),

    "./srcfiles/css/fontawesome/fa-brands-400.woff2": ( "/css/fontawesome/webfonts/fa-brands-400.woff2", "font/woff2" ),
    "./srcfiles/css/fontawesome/fa-regular-400.woff2": ( "/css/fontawesome/webfonts/fa-regular-400.woff2", "font/woff2" ),
    "./srcfiles/css/fontawesome/fa-solid-900.woff2": ( "/css/fontawesome/webfonts/fa-solid-900.woff2", "font/woff2" ),
    "./srcfiles/css/fontawesome/fa-v4compatibility.woff2": ( "/css/fontawesome/webfonts/fa-v4compatibility.woff2", "font/woff2" ),

    "./srcfiles/x0/userFunctions.js": ( "/userFunctions.js", "text/javascript" ),
    "./srcfiles/x0/sysHelper.js": ( "/sysHelper.js", "text/javascript" ),
    "./srcfiles/x0/sysSourceObjectHandler.js": ( "/sysSourceObjectHandler.js", "text/javascript" ),
    "./srcfiles/x0/sysRequestDataHandler.js": ( "/sysRequestDataHandler.js", "text/javascript" ),
    "./srcfiles/x0/sysReactor.js": ( "/sysReactor.js", "text/javascript" ),
    "./srcfiles/x0/sysRandomNr.js": ( "/sysRandomNr.js", "text/javascript" ),
    "./srcfiles/x0/sysBase64.js": ( "/sysBase64.js", "text/javascript" ),
    "./srcfiles/x0/sysBaseDOMElement.js": ( "/sysBaseDOMElement.js", "text/javascript" ),
    "./srcfiles/x0/sysBaseObject.js": ( "/sysBaseObject.js", "text/javascript" ),
    "./srcfiles/x0/sysXMLRPCRequest.js": ( "/sysXMLRPCRequest.js", "text/javascript" ),
    "./srcfiles/x0/sysXMLRPCBaseSyncLoader.js": ( "/sysXMLRPCBaseSyncLoader.js", "text/javascript" ),
    "./srcfiles/x0/sysJSONData.js": ( "/sysJSONData.js", "text/javascript" ),
    "./srcfiles/x0/sysText.js": ( "/sysText.js", "text/javascript" ),
    "./srcfiles/x0/sysServiceConnector.js": ( "/sysServiceConnector.js", "text/javascript" ),
    "./srcfiles/x0/sysRTPagination.js": ( "/sysRTPagination.js", "text/javascript" ),
    "./srcfiles/x0/sysRTFormSectionHeader.js": ( "/sysRTFormSectionHeader.js", "text/javascript" ),
    "./srcfiles/x0/sysObjLink.js": ( "/sysObjLink.js", "text/javascript" ),
    "./srcfiles/x0/sysObjLinkExternal.js": ( "/sysObjLinkExternal.js", "text/javascript" ),
    "./srcfiles/x0/sysObjSQLText.js": ( "/sysObjSQLText.js", "text/javascript" ),
    "./srcfiles/x0/sysObjDiv.js": ( "/sysObjDiv.js", "text/javascript" ),
    "./srcfiles/x0/sysObjContextMenu.js": ( "/sysObjContextMenu.js", "text/javascript" ),
    "./srcfiles/x0/sysScreenOverlay.js": ( "/sysScreenOverlay.js", "text/javascript" ),
    "./srcfiles/x0/sysObjButton.js": ( "/sysObjButton.js", "text/javascript" ),
    "./srcfiles/x0/sysObjButtonInternal.js": ( "/sysObjButtonInternal.js", "text/javascript" ),
    "./srcfiles/x0/sysObjButtonCallback.js": ( "/sysObjButtonCallback.js", "text/javascript" ),
    "./srcfiles/x0/sysObjFileUpload.js": ( "/sysObjFileUpload.js", "text/javascript" ),
    "./srcfiles/x0/sysObjErrorContainer.js": ( "/sysObjErrorContainer.js", "text/javascript" ),
    "./srcfiles/x0/sysFormfieldOnChangeHandler.js": ( "/sysFormfieldOnChangeHandler.js", "text/javascript" ),
    "./srcfiles/x0/sysIntervalHandler.js": ( "/sysIntervalHandler.js", "text/javascript" ),
    "./srcfiles/x0/sysFormfieldValidate.js": ( "/sysFormfieldValidate.js", "text/javascript" ),
    "./srcfiles/x0/sysObjFormfieldItem.js": ( "/sysObjFormfieldItem.js", "text/javascript" ),
    "./srcfiles/x0/sysGlobalData.js": ( "/sysGlobalData.js", "text/javascript" ),
    "./srcfiles/x0/sysScreen.js": ( "/sysScreen.js", "text/javascript" ),
    "./srcfiles/x0/sysObjectLoader.js": ( "/sysObjectLoader.js", "text/javascript" ),
    "./srcfiles/x0/sysObjList.js": ( "/sysObjList.js", "text/javascript" ),
    "./srcfiles/x0/sysObjTabContainer.js": ( "/sysObjTabContainer.js", "text/javascript" ),
    "./srcfiles/x0/sysObjFormfieldList.js": ( "/sysObjFormfieldList.js", "text/javascript" ),
    "./srcfiles/x0/sysObjDynRadioList.js": ( "/sysObjDynRadioList.js", "text/javascript" ),
    "./srcfiles/x0/sysObjOpenCloseContainer.js": ( "/sysObjOpenCloseContainer.js", "text/javascript" ),
    "./srcfiles/x0/sysObjTreeSimple.js": ( "/sysObjTreeSimple.js", "text/javascript" ),
    "./srcfiles/x0/sysGridGenerator.js": ( "/sysGridGenerator.js", "text/javascript" ),
    "./srcfiles/x0/sysFactory.js": ( "/sysFactory.js", "text/javascript" ),
    "./srcfiles/x0/sysAsyncNotify.js": ( "/sysAsyncNotify.js", "text/javascript" ),
    "./srcfiles/x0/sysAsyncNotifyIndicator.js": ( "/sysAsyncNotifyIndicator.js", "text/javascript" ),
    "./srcfiles/x0/sysAsyncNotifyIndicatorItem.js": ( "/sysAsyncNotifyIndicatorItem.js", "text/javascript" ),
    "./srcfiles/x0/sysAsyncNotifyMsgHandler.js": ( "/sysAsyncNotifyMsgHandler.js", "text/javascript" ),

    "./srcfiles/x0/sysInitOnLoad.js": ( "/sysInitOnLoad.js", "text/javascript" ),

    "./srcfiles/x0/meta/text-data.json": ( "/text-data.json", "application/json" ),
    "./srcfiles/x0/meta/menu.json": ( "/menu.json", "application/json" ),
    "./srcfiles/x0/meta/object.json": ( "/object.json", "application/json" ),
    "./srcfiles/x0/meta/skeleton.json": ( "/skeleton.json", "application/json" )
}
